/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jackmeng_tailwind_sys_TailwindMath */

#ifndef _Included_com_jackmeng_tailwind_sys_TailwindMath
#define _Included_com_jackmeng_tailwind_sys_TailwindMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jackmeng_tailwind_sys_TailwindMath
 * Method:    normalize_mantissa_iee
 * Signature: ([D)V
 */
JNIEXPORT void JNICALL Java_com_jackmeng_tailwind_sys_1TailwindMath_normalize_1mantissa_1iee
  (JNIEnv *, jclass, jdoubleArray);

/*
 * Class:     com_jackmeng_tailwind_sys_TailwindMath
 * Method:    normalize_samples
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_com_jackmeng_tailwind_sys_1TailwindMath_normalize_1samples
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     com_jackmeng_tailwind_sys_TailwindMath
 * Method:    window_func_1
 * Signature: ([FI)[F
 */
JNIEXPORT jfloatArray JNICALL Java_com_jackmeng_tailwind_sys_1TailwindMath_window_1func_11
  (JNIEnv *, jclass, jfloatArray, jint);

#ifdef __cplusplus
}
#endif
#endif
