/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jackmeng_platform_sys_SimpleMaffs */

#ifndef _Included_com_jackmeng_platform_sys_SimpleMaffs
#define _Included_com_jackmeng_platform_sys_SimpleMaffs
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jackmeng_platform_sys_SimpleMaffs
 * Method:    simplify_ratio
 * Signature: (JJ)[J
 */
JNIEXPORT jlongArray JNICALL Java_com_jackmeng_platform_sys_1SimpleMaffs_simplify_1ratio
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
