/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jackmeng_util_use_Commons_primitives_Math */

#ifndef _Included_com_jackmeng_util_use_Commons_primitives_Math
#define _Included_com_jackmeng_util_use_Commons_primitives_Math
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jackmeng_util_use_Commons_primitives_Math
 * Method:    rnd_1
 * Signature: ([J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jackmeng_util_use_1Commons_00024primitives_1Math_rnd_11
  (JNIEnv *, jobject, jlongArray);

/*
 * Class:     com_jackmeng_util_use_Commons_primitives_Math
 * Method:    exp_dev
 * Signature: ([J)F
 */
JNIEXPORT jfloat JNICALL Java_com_jackmeng_util_use_1Commons_00024primitives_1Math_exp_1dev
  (JNIEnv *, jobject, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
