/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jackmeng_sys_sys_out */

#ifndef _Included_com_jackmeng_sys_sys_out
#define _Included_com_jackmeng_sys_sys_out
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jackmeng_sys_sys_out
 * Method:    out
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jackmeng_sys_sys_1out_out
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_jackmeng_sys_sys_out
 * Method:    debug
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_jackmeng_sys_sys_1out_debug
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_jackmeng_sys_sys_out
 * Method:    f_out
 * Signature: (Ljava/lang/String;[Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_jackmeng_sys_sys_1out_f_1out
  (JNIEnv *, jobject, jstring, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
